import 'package:tonic/tonic.dart';

Map<String, dynamic> diatonicMajorModes = {
  'Ionian': {
    'scaleStepsRoman': ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'],
    'intervals': [0, 2, 4, 5, 7, 9, 11],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      Interval.M3,
      Interval.P4,
      null,
      Interval.P5,
      null,
      Interval.M6,
      null,
      Interval.M7
    ],
  },
  'Dorian': {
    'scaleStepsRoman': ['I', 'II', '♭III', 'IV', 'V', 'VI', '♭VII'],
    'intervals': [0, 2, 3, 5, 7, 9, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      Interval.m3,
      null,
      Interval.P4,
      null,
      Interval.P5,
      null,
      Interval.M6,
      Interval.m7,
      null,
    ],
  },
  'Phrygian': {
    'scaleStepsRoman': ['I', '♭II', '♭III', 'IV', 'V', '♭VI', '♭VII'],
    'intervals': [0, 1, 3, 5, 7, 8, 10],
    'scaleDegrees': [
      Interval.P1,
      Interval.m2,
      null,
      Interval.m3,
      null,
      Interval.P4,
      null,
      Interval.P5,
      Interval.m6,
      null,
      Interval.m7,
      null,
    ],
  },
  'Lydian': {
    'scaleStepsRoman': ['I', 'II', 'III', '♯IV', 'V', 'VI', 'VII'],
    'intervals': [0, 2, 4, 6, 7, 9, 11],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      Interval.M3,
      null,
      Interval.A4, // Augmented 4th (Lydian characteristic note)
      Interval.P5,
      null,
      Interval.M6,
      null,
      Interval.M7
    ],
  }, // 'aug' represents augmented
  'Mixolydian': {
    'scaleStepsRoman': ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'],
    'intervals': [0, 2, 4, 5, 7, 9, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      Interval.M3,
      Interval.P4,
      null,
      Interval.P5,
      null,
      Interval.M6,
      Interval.m7,
      null,
    ],
  },
  'Aeolian': {
    'scaleStepsRoman': ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'],
    'intervals': [0, 2, 4, 5, 7, 9, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      Interval.m3,
      null,
      Interval.P4,
      null,
      Interval.P5,
      Interval.m6,
      null,
      Interval.m7,
      null,
    ],
  },
  'Locrian': {
    'scaleStepsRoman': ['I', 'II', '♭III', 'IV', '♭V', '♭VI', '♭VII'],
    'intervals': [0, 1, 3, 5, 6, 8, 10],
    'scaleDegrees': [
      Interval.P1,
      Interval.m2,
      null,
      Interval.m3,
      null,
      Interval.P4,
      Interval.d5,
      null,
      Interval.m6,
      null,
      Interval.m7,
      null,
    ],
  },
};
