import 'package:tonic/tonic.dart';

Map hexatonics = {
  'Whole Tone': {
    'scaleStepsRoman': ['I', 'II', 'III', '♯IV', '♯V', '♯VI'],
    'intervals': [0, 2, 4, 6, 8, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      Interval.M3,
      null,
      Interval.A4,
      null,
      Interval.A5,
      null,
      Interval.A6,
      null,
    ],
  },
  'Major Hexatonic': {
    'scaleStepsRoman': ['I', 'II', 'III', 'IV', 'V', 'VI'],
    'intervals': [0, 2, 4, 5, 7, 9],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      Interval.M3,
      Interval.P4,
      null,
      Interval.P5,
      null,
      Interval.M6,
      null,
      null,
    ],
  },
  'Minor Hexatonic': {
    'scaleStepsRoman': ['I', 'II', '♭III', 'IV', 'V', '♭VII'],
    'triad': [Interval.P1, Interval.m3, Interval.P5],
    'tetrade': [Interval.P1, Interval.m3, Interval.P5, Interval.m7],
    'intervals': [0, 2, 3, 5, 7, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      Interval.m3,
      null,
      Interval.P4,
      null,
      Interval.P5,
      null,
      null,
      Interval.m7,
      null,
    ],
  },
  'Ritsu Onkai': {
    'scaleStepsRoman': ['I', '♭II', '♭III', 'IV', '♭VI', '♭VII'],
    'intervals': [0, 1, 3, 5, 8, 10],
    'scaleDegrees': [
      Interval.P1,
      Interval.m2,
      null,
      Interval.m3,
      null,
      Interval.P4,
      null,
      null,
      Interval.m6,
      null,
      Interval.m7,
      null,
    ],
  },
  'Raga Kumud': {
    'scaleStepsRoman': ['I', 'II', 'III', 'V', 'VI', 'VII'],
    'intervals': [0, 2, 4, 7, 9, 11],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      Interval.M3,
      null,
      null,
      Interval.P5,
      null,
      Interval.M6,
      null,
      Interval.M7,
    ],
  },
  'Mixolydian Hexatonic': {
    'scaleStepsRoman': ['I', 'II', 'IV', 'V', 'VI', '♭VII'],
    'intervals': [0, 2, 5, 7, 9, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      null,
      Interval.P4,
      null,
      Interval.P5,
      null,
      Interval.M6,
      null,
      Interval.m7,
    ],
  },
  'Phrygian Hexatonic': {
    'scaleStepsRoman': ['I', '♭III', 'IV', 'V', '♭VI', '♭VII'],
    'intervals': [0, 3, 5, 7, 8, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      null,
      Interval.m3,
      null,
      Interval.P4,
      null,
      Interval.P5,
      Interval.m6,
      null,
      Interval.m7,
      null,
    ],
  },
};
