import 'package:tonic/tonic.dart';

Map<String, dynamic> melodicMinorModes = {
  'Jazz Minor': {
    'scaleStepsRoman': ['I', 'II', '♭III', 'IV', 'V', 'VI', 'VII'],
    'intervals': [0, 2, 3, 5, 7, 9, 11],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      Interval.m3,
      null,
      Interval.P4,
      null,
      Interval.P5,
      null,
      Interval.M6,
      null,
      Interval.M7
    ],
  },
  'Dorian ♭2': {
    'scaleStepsRoman': ['I', 'II', '♭III', 'IV', 'V', 'VI', 'VII'],
    'intervals': [0, 1, 3, 5, 7, 9, 11],
    'scaleDegrees': [
      Interval.P1,
      Interval.m2,
      null,
      Interval.m3,
      null,
      Interval.P4,
      null,
      Interval.P5,
      null,
      Interval.M6,
      null,
      Interval.M7
    ],
  },
  'Lydian Augmented': {
    'scaleStepsRoman': ['I', 'II', 'III', '♯IV', '♯V', 'VI', 'VII'],
    'intervals': [0, 2, 4, 6, 8, 9, 11],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      Interval.M3,
      null,
      Interval.A4,
      null,
      Interval.A5,
      Interval.M6,
      null,
      Interval.M7
    ],
  },
  'Lydian Dominant': {
    'scaleStepsRoman': ['I', 'II', 'III', '♯IV', 'V', 'VI', '♭VII'],
    'intervals': [0, 2, 4, 6, 8, 9, 1],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      Interval.M3,
      null,
      Interval.A4,
      Interval.P5,
      null,
      Interval.M6,
      Interval.m7,
      null,
    ],
  },
  'Mixolydian ♭6': {
    'scaleStepsRoman': ['I', 'II', '♭III', 'IV', 'V', '♭VI', '♭VII'],
    'intervals': [0, 2, 3, 5, 7, 8, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      Interval.m3,
      null,
      Interval.P4,
      null,
      Interval.P5,
      Interval.m6,
      null,
      Interval.m7,
      null,
    ],
  },
  'Semilocrian': {
    'scaleStepsRoman': ['I', '♭II', '♭III', 'IV', '♭V', '♭VI', '♭VII'],
    'intervals': [0, 1, 3, 5, 6, 8, 10],
    'scaleDegrees': [
      Interval.P1,
      Interval.m2,
      null,
      Interval.m3,
      null,
      Interval.P4,
      Interval.d5,
      null,
      Interval.m6,
      null,
      Interval.m7,
      null,
    ],
  },
  'Superlocrian': {
    'scaleStepsRoman': ['I', '♭II', '♭III', '♭IV', '♭V', '♭VI', '♭VII'],
    'intervals': [0, 1, 3, 4, 6, 8, 10],
    'scaleDegrees': [
      Interval.P1,
      Interval.m2,
      null,
      Interval.m3,
      Interval.d4,
      null,
      Interval.d5,
      null,
      Interval.m6,
      null,
      Interval.m7,
      null,
    ],
  },
};
